import '../entities/daily_focus_statistics.dart';
import '../entities/focus_session.dart';
import '../entities/statistics_date_range.dart';

/// Groups focus sessions by local calendar day with zero-fill for empty days.
class GroupSessionsByDayUseCase {
  /// Creates a [GroupSessionsByDayUseCase] instance.
  const GroupSessionsByDayUseCase();

  /// Returns one [DailyFocusStatistics] per local calendar day in [range],
  /// ordered chronologically.
  ///
  /// Range boundaries are converted from UTC to local time. Calendar days
  /// are generated by constructing each local date explicitly instead of
  /// calculating elapsed 24-hour periods, so daylight-saving changes do not
  /// affect the number of generated days.
  List<DailyFocusStatistics> call(
    List<FocusSession> sessions,
    StatisticsDateRange range,
  ) {
    final localStart = range.start.toLocal();
    final localEnd = range.end.toLocal();

    final startDay = DateTime(
      localStart.year,
      localStart.month,
      localStart.day,
    );

    final endDay = DateTime(localEnd.year, localEnd.month, localEnd.day);

    final days = <DateTime>[];
    var currentDay = startDay;

    while (currentDay.isBefore(endDay)) {
      days.add(currentDay);

      currentDay = DateTime(
        currentDay.year,
        currentDay.month,
        currentDay.day + 1,
      );
    }

    final buckets = <DateTime, _DayBucket>{
      for (final day in days) day: _DayBucket(),
    };

    for (final session in sessions) {
      final localTime = session.startedAt.toLocal();

      final sessionDay = DateTime(
        localTime.year,
        localTime.month,
        localTime.day,
      );

      final bucket = buckets[sessionDay];

      // Ignore sessions outside the supplied date range.
      if (bucket == null) {
        continue;
      }

      bucket.totalFocusedSeconds += session.actualDurationSeconds;
      bucket.sessionCount++;
    }

    return days
        .map((day) {
          final bucket = buckets[day]!;

          return DailyFocusStatistics(
            date: day,
            totalFocusedSeconds: bucket.totalFocusedSeconds,
            sessionCount: bucket.sessionCount,
          );
        })
        .toList(growable: false);
  }
}

/// Mutable accumulator used only while grouping sessions.
class _DayBucket {
  int totalFocusedSeconds = 0;
  int sessionCount = 0;
}
